import { defineField, defineType } from "sanity";

export const postSchema = defineType({
  name: "post",
  title: "Insight Article",
  type: "document",
  fields: [
    defineField({
      name: "language",
      title: "Language",
      type: "string",
      readOnly: true,
      hidden: true,
    }),
    defineField({ name: "title", title: "Title", type: "string", validation: (R) => R.required().max(200) }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (R) => R.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      options: {
        list: [
          { title: "Wealth Management", value: "wealth" },
          { title: "Family Office", value: "family" },
          { title: "Structuring & Tax", value: "structuring" },
          { title: "M&A & Corporate", value: "ma" },
          { title: "Special Solutions", value: "special" },
        ],
        layout: "dropdown",
      },
      validation: (R) => R.required(),
    }),
    defineField({ name: "coverImage", title: "Cover Image", type: "image", options: { hotspot: true } }),
    defineField({ name: "excerpt", title: "Excerpt", type: "text", rows: 3, validation: (R) => R.max(300) }),
    defineField({
      name: "readTime",
      title: "Read Time (minutes)",
      type: "number",
      validation: (R) => R.required().min(1).max(60),
    }),
    defineField({ name: "publishedAt", title: "Published At", type: "datetime", validation: (R) => R.required() }),
    // --- Pipeline-managed fields (ADR-018) ----------------------------
    defineField({
      name: "keyTakeaway",
      title: "Key Takeaway",
      type: "text",
      rows: 2,
      description: "One-sentence summary; used in social-media captions and as excerpt fallback",
      validation: (R) => R.max(280),
    }),
    defineField({
      name: "coverImageAlt",
      title: "Cover Image Alt Text",
      type: "string",
      description: "Accessibility text for the cover image",
      validation: (R) => R.max(200),
    }),
    defineField({
      name: "sourceUrl",
      title: "Source URL",
      type: "url",
      description: "Original news article used as a peg (pipeline-only)",
      readOnly: true,
    }),
    defineField({
      name: "topicId",
      title: "Topic ID",
      type: "string",
      description: "Stable hash of the source story for dedup (pipeline-only)",
      readOnly: true,
      hidden: true,
    }),
    defineField({
      name: "generatedBy",
      title: "Generated By",
      type: "string",
      options: {
        list: [
          { title: "Pipeline (AI)", value: "pipeline" },
          { title: "Human", value: "human" },
        ],
      },
      initialValue: "human",
      readOnly: ({ document }) => document?.generatedBy === "pipeline",
    }),
    // -----------------------------------------------------------------
    defineField({
      name: "tableOfContents",
      title: "Table of Contents",
      type: "array",
      of: [{ type: "string" }],
      description: "Section headings shown in the sidebar TOC",
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [
        {
          type: "block",
          styles: [
            { title: "Normal", value: "normal" },
            { title: "H2", value: "h2" },
            { title: "H3", value: "h3" },
            { title: "Quote", value: "blockquote" },
          ],
          marks: {
            decorators: [
              { title: "Strong", value: "strong" },
              { title: "Emphasis", value: "em" },
            ],
            annotations: [
              {
                name: "link",
                type: "object",
                title: "Link",
                fields: [{ name: "href", type: "url", title: "URL" }],
              },
            ],
          },
        },
        { type: "image", options: { hotspot: true }, fields: [{ name: "alt", type: "string", title: "Alt text" }] },
      ],
    }),
  ],
  orderings: [
    {
      title: "Published Date, New",
      name: "publishedAtDesc",
      by: [{ field: "publishedAt", direction: "desc" }],
    },
    {
      title: "Language, then Published Date",
      name: "langPublishedAt",
      by: [
        { field: "language", direction: "asc" },
        { field: "publishedAt", direction: "desc" },
      ],
    },
  ],
  preview: {
    select: { title: "title", media: "coverImage", subtitle: "category", language: "language" },
    prepare({ title, media, subtitle, language }) {
      return {
        title,
        media,
        subtitle: language ? `[${String(language).toUpperCase()}] ${subtitle ?? ""}` : subtitle,
      };
    },
  },
});
